#!/usr/bin/env bash
set -Eeuo pipefail

# To install govulncheck see https://go.dev/doc/security/vuln/
# To install staticcheck see https://staticcheck.dev/docs/getting-started/#installation
# To install golangci-lint see https://golangci-lint.run/welcome/install/
# To install gosec see https://github.com/securego/gosec#local-installation

env GOOS=linux GOARCH=amd64 go vet ./...
env GOOS=linux GOARCH=amd64 govulncheck ./...
env GOOS=linux GOARCH=amd64 staticcheck -checks "all,-ST1000" ./...
env GOOS=linux GOARCH=amd64 golangci-lint run
env GOOS=linux GOARCH=amd64 gosec -quiet -exclude=G103,G104,G114,G115,G204,G304,G402,G407 ./...
