package metrics

const (
	DRKeyCacheKeysInsertedH = "The total number of DRKeys inserted into cache"
	DRKeyCacheKeysInsertedN = "timeservice_drkey_cache_keys_inserted"
	DRKeyCacheKeysExpiredH  = "The total number of DRKeys expired in the cache"
	DRKeyCacheKeysExpiredN  = "timeservice_drkey_cache_keys_expired"
	DRKeyCacheKeysReplacedH = "The total number of DRKeys replaced in the cache"
	DRKeyCacheKeysReplacedN = "timeservice_drkey_cache_keys_replaced"

	IPClientPktsReceivedH             = "The total number of packets received via IP"
	IPClientPktsReceivedN             = "timeservice_ip_client_pkts_received"
	IPClientReqsSentH                 = "The total number of requests sent via IP"
	IPClientReqsSentN                 = "timeservice_ip_client_reqs_sent"
	IPClientReqsSentInterleavedH      = "The total number of requests sent via IP in interleaved mode"
	IPClientReqsSentInterleavedN      = "timeservice_ip_client_reqs_sent_interleaved"
	IPClientRespsAcceptedH            = "The total number of responses accepted via IP"
	IPClientRespsAcceptedN            = "timeservice_ip_client_resps_accepted"
	IPClientRespsAcceptedInterleavedH = "The total number of responses accepted via IP in interleaved mode"
	IPClientRespsAcceptedInterleavedN = "timeservice_ip_client_resps_accepted_interleaved"

	IPServerPktsReceivedH = "The total number of packets received via IP"
	IPServerPktsReceivedN = "timeservice_ip_server_pkts_received"
	IPServerReqsAcceptedH = "The total number of requests accepted via IP"
	IPServerReqsAcceptedN = "timeservice_ip_server_reqs_accepted"
	IPServerReqsServedH   = "The total number of requests served via IP"
	IPServerReqsServedN   = "timeservice_ip_server_reqs_served"

	SCIONClientPktsAuthenticatedH        = "The total number of packets authenticated via SCION"
	SCIONClientPktsAuthenticatedN        = "timeservice_scion_client_pkts_authenticated"
	SCIONClientPktsReceivedH             = "The total number of packets received via SCION"
	SCIONClientPktsReceivedN             = "timeservice_scion_client_pkts_received"
	SCIONClientReqsSentH                 = "The total number of requests sent via SCION"
	SCIONClientReqsSentN                 = "timeservice_scion_client_reqs_sent"
	SCIONClientReqsSentInterleavedH      = "The total number of requests sent via SCION in interleaved mode"
	SCIONClientReqsSentInterleavedN      = "timeservice_scion_client_reqs_sent_interleaved"
	SCIONClientRespsAcceptedH            = "The total number of responses accepted via SCION"
	SCIONClientRespsAcceptedN            = "timeservice_scion_client_resps_accepted"
	SCIONClientRespsAcceptedInterleavedH = "The total number of responses accepted via SCION in interleaved mode"
	SCIONClientRespsAcceptedInterleavedN = "timeservice_scion_client_resps_accepted_interleaved"

	SCIONServerPktsAuthenticatedH = "The total number of packets authenticated via SCION"
	SCIONServerPktsAuthenticatedN = "timeservice_scion_server_pkts_authenticated"
	SCIONServerPktsForwardedH     = "The total number of packets forwarded via SCION"
	SCIONServerPktsForwardedN     = "timeservice_scion_server_pkts_forwarded"
	SCIONServerPktsReceivedH      = "The total number of packets received via SCION"
	SCIONServerPktsReceivedN      = "timeservice_scion_server_pkts_received"
	SCIONServerReqsAcceptedH      = "The total number of requests accepted via SCION"
	SCIONServerReqsAcceptedN      = "timeservice_scion_server_reqs_accepted"
	SCIONServerReqsServedH        = "The total number of requests served via SCION"
	SCIONServerReqsServedN        = "timeservice_scion_server_reqs_served"

	ServerReqsServedInterleavedH = "The total number of requests served in interleaved mode"
	ServerReqsServedInterleavedN = "timeservice_server_reqs_served_interleaved"
	ServerRxtIncrementsH         = "The total number of RX timestamps incremented to ensure monotonicity"
	ServerRxtIncrementsN         = "timeservice_server_rxt_increments"
	ServerTssItemsH              = "The total number of timestamp store items stored (one item per client)"
	ServerTssItemsN              = "timeservice_server_tss_items"
	ServerTssValuesH             = "The total number of timestamp store values stored"
	ServerTssValuesN             = "timeservice_server_tss_values"
	ServerTxtIncrementsAfterH    = "The total number of TX timestamps incremented after transfer to ensure monotonicity"
	ServerTxtIncrementsAfterN    = "timeservice_server_txt_increments_after"
	ServerTxtIncrementsBeforeH   = "The total number of TX timestamps incremented before transfer to ensure monotonicity"
	ServerTxtIncrementsBeforeN   = "timeservice_server_txt_increments_before"

	SyncGlobalCorrH = "The current clock correction applied based on global sync"
	SyncGlobalCorrN = "timeservice_sync_global_corr"
	SyncLocalCorrH  = "The current clock correction applied based on local sync"
	SyncLocalCorrN  = "timeservice_sync_local_corr"
)
